// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Data.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    [Migration("20260918142535_SeedCoupons")]
    partial class SeedCoupons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10000,
                            Description = "Discounted on Samsung newly launch z fold smartphone",
                            ProductName = "Samsung Galaxy Z Fold"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 15000,
                            Description = "Discounted on Samsung newly launch z fold tri smartphone",
                            ProductName = "Samsung Galaxy Z Fold Tri"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 12000,
                            Description = "Discounted on apple newly launch iphone duo smartphone",
                            ProductName = "Iphone Duo"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 6000,
                            Description = "Discounted on apple newly launch iphone 18 pro max smartphone",
                            ProductName = "Iphone 18 pro max"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
