services:
  orderdb:
    image: mcr.microsoft.com/mssql/server
    container_name: orderdb
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "AdM!n78r9"
    restart: "always"
    # ports:
    #  - "1433:1433"
    volumes:
      - sqlserver_order:/var/opt/mssql
    networks:
      - EShop-Microservice

  order.api:
    image: order-api
    build:
      context: .
      dockerfile: ./Services/Ordering/Ordering.API/Dockerfile
    container_name: order-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
      - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=AdM!n78r9;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - orderdb
    ports:
      - "6004:8000"
    networks:
      - EShop-Microservice

volumes:
  sqlserver_order:

networks:
  EShop-Microservice:
    driver: bridge
