services:
  basketdb:
    image: postgres:18.4
    container_name: basketdb
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=BasketDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql
    networks:
      - EShop-Microservice

  distributedcached:
    image: redis
    container_name: distributedcached
    restart: always
    ports:
      - "6379:6379"
    networks:
      - EShop-Microservice

  # basket.api:
  #   image: basket-api
  #   build:
  #     context: .
  #     dockerfile: ./Services/Basket/Basket.API/Dockerfile
  #   container_name: basket-api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8000
  #     - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDB;User Id=postgres;Password=example
  #   depends_on:
  #     - basketdb
  #   ports:
  #     - "6002:8000"
  #   networks:
  #     - EShop-Microservice

volumes:
  postgres_basket:

networks:
  EShop-Microservice:
    driver: bridge
